# Generated by Django 3.2 on 2023-12-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231203_0929'),
        ('reviews', '0004_rename_genre_title_genres'),
    ]

    operations = [
    ]
